name: "CI"

on: workflow_dispatch
jobs: 
  mydemojob: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: FooBar 
        run: |
          pwd
          ls -la
          echo Hello!
      - name: show context
        run: echo "${{ toJSON(github) }}"
  testNode:
    needs: [mydemojob]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 16, 18 ]
    steps:
      - name: get repository code
        uses: actions/checkout@v4
      - name: testing
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: node -v
      - run: npm -v
      - name: show-secret
        run: echo ${{ secrets.MY_SECRET_TOKEN }}
