name: "CI"

on: workflow_dispatch
jobs: 
  mydemojob: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: FooBar 
        run: |
          pwd
          ls -la
          echo Hello!
  testNOde: 
    needs: [mydemojob]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 16, 18 ]
    name: Node ${{ matrix.node }} sample
    steps:
      - name: testing
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm -v
      - run: node -v
