name: "CI"

on: workflow_dispatch
jobs: 
  mydemojob: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: FooBar 
        run: |
          pwd
          ls -la
          echo Hello!
